apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: jefrinpeter/todoapp-image:latest  # Docker Hub image name
          ports:
            - containerPort: 3000
          imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
