apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  type: NodePort  # Exposes the app on a port outside of the cluster
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Exposed port on Minikube
